project_name: skipper

builds:
  - binary: skipper
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    ldflags:
      - -s -w -X github.com/jerryagbesi/skipper/cmd.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: JerryAgbesi
    name: skipper
